
name: platify
description: "Financial assistant application"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  pocketbase: ^0.23.0+1
  
  # Isar Community packages
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  uuid: ^4.5.2
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Isar Community code generator and build_runner
  isar_community_generator: ^3.3.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
