name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.5+1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  uuid: ^4.4.0
  path_provider: ^2.1.5
  drift: ^2.30.0
  sqlite3_flutter_libs: ^0.5.41
  path: ^1.9.1
  fl_chart: ^1.1.1
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.10.4
  drift_dev: ^2.30.0

flutter:
  uses-material-design: true
